services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile.sqlsrv
    volumes:
      # TODO Update storage location as desired
      - ./surveys:/var/www/html/upload/surveys
      # - ./entrypoint.sh:/usr/local/bin/entrypoint.sh 
      # - ./config.php:/var/www/html/application/config/config.php
    networks:
      - limesurvey-db
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=10.1.34.3"
      # TODO set passwords
      - "DB_TYPE=sqlsrv"
      - "DB_USERNAME=sa"
      - "DB_PASSWORD=SA@uni!$02"
      - "DB_NAME=lime"
      # LimeSurveyDb"
      - "ADMIN_PASSWORD=admin"
      # If you require an empty table prefix, use a space as the DB_TABLE_PREFIX
      - "DB_TABLE_PREFIX=lime_"
      - "ADMIN_EMAIL=test@example.com"

#   lime-db:
#     image: mariadb:11.4
#     networks:
#       - limesurvey-db
#     environment:
#       - "MYSQL_USER=limesurvey"
#       - "MYSQL_DATABASE=limesurvey"
#       # TODO set passwords
#       - "MYSQL_PASSWORD=abcd@1234"
#       - "MYSQL_ROOT_PASSWORD=abcd@1234"
      
# volumes:
#   my-volume:

networks:
  limesurvey-db:
    driver: bridge
